The React 1.0.2 profile relies on Webpack to bundle React components into browser-ready JavaScript bundles, which can then be loaded via the Grails Asset Pipeline. The default application includes a single "index" bundle which is rendered on the index page. Let's set up a new bundle for our `Garage` app.

In `webpack.config.js`, edit the `entry` section and add a line to load our `garage.js` file, as seen below:

[source,javascript]
----
var path = require('path');

module.exports = {
    entry: {
        index: './src/main/webapp/app/app.js',     <2>
        garage: './src/main/webapp/app/garage.js'  <1>
    },
    //...
----
<1> Add the path to `garage.js` as the `garage` entry point
<2> Don't forget the comma!

This will cause Webpack to bundle two different React apps, "index" and "garage". We also need to configure Webpack to output separate bundles for each React app, so we can load them on different pages of our Grails app.

In `webpack.config.js`, edit the `output` section and change the `filename` line as shown below:

[source,javascript]
----
    //...
    output: {
        path: './grails-app/assets/javascripts',
        publicPath: '/assets/',
        filename: 'bundle-[name].js'  // <1>
    },
    //...
----
<1> Add `-[name]` to the filename property

Now when we start up our Grails app (or run `./gradlew webpack`), Webpack will generate two bundles, one called `bundle-index.js` and one called `bundle-garage.js`. We can load these bundles on our page using the Grails Asset Pipeline tags.

[NOTE]
====
Since we changed the filename of the bundle, we'll need to quickly update our original `index.gsp` page to use the new name.

Edit `grails-app/views/index.gsp`, line 66:

[source,xml]
----
        <div id="app"></div>
        <asset:javascript src="bundle-index.js" /> // <1>
----
<1> Change "bundle.js" to "bundle-index.js"

====


Now we are finally ready to create a home page for our `Garage` app. Create a new Grails controller using a local Grails installation or `./grailsw`

[source,bash]
----
./grailsw create-controller com.example.GarageController
----

Make sure that `GarageController` contains a single `index` action.

[source,groovy]
----
package com.example

class GarageController {
    def index() { }
}
----

Now, create a simple `index.gsp` page under `grails-app/views/garage`:

[source,xml]
----
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Garage</title>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>

<div id="content" role="main">
    <section class="row colset-2-its">
        <div id="garage"></div>
        <asset:javascript src="bundle-garage.js" />
    </section>
</div>

</body>
</html>
----

Restart the app, and browse to `http://localhost:8080/garage`. You should see our new React app loaded on the page, with a single hard-coded row of data.

