The React profile includes some default React sample code. Feel free to run the app as is if you want to see the sample in action.

Let's start by creating our domain model for the application.

[source,bash]
----
$ grails create-domain-class com.example.Vehicle
$ grails create-domain-class com.example.Driver
$ grails create-domain-class com.example.Make
$ grails create-domain-class com.example.Model
----

Now let's edit our domain class under `grails-app/domain/com/example/`. We'll add some properties and the `@Resource` annotation.

[source,groovy]
.grails-app/grails-app/domain/com/example/Vehicle.groovy
----
include::{sourceDir}/grails-app/domain/com/example/Vehicle.groovy[]
----

[source,groovy]
.grails-app/grails-app/domain/com/example/Driver.groovy
----
include::{sourceDir}/grails-app/domain/com/example/Driver.groovy[]
----

[source,groovy]
.grails-app/grails-app/domain/com/example/Make.groovy
----
include::{sourceDir}/grails-app/domain/com/example/Make.groovy[]
----

[source,groovy]
.grails-app/grails-app/domain/com/example/Model.groovy
----
include::{sourceDir}/grails-app/domain/com/example/Model.groovy[]
----

Since we've added the `@Resource` annotation to our domain classes, Grails will generate RESTful URL mappings for each of them. Let's preload some data:

[source,groovy]
.grails-app/init/building/a/react/app/BootStrap.groovy
----
include::{sourceDir}/grails-app/init/building/a/react/app/BootStrap.groovy[]
----
